cache:
    paths:
    - node_modules

stages:
    - build
    - test
    - deploy

before_script:
    - bin/_pre-setup
    - yarn install

build:
    stage: build
    tags:
        - javascript
        - scss
    script:
        - yarn run build
    artifacts:
      paths:
        - .next
        - build
      expire_in: 1 day

code_quality:
    stage: test
    tags:
        - javascript
        - scss
    script:
        - yarn run stylelint
        - yarn run lint
    allow_failure: true
